### ISSUE TITLE
建议增加命令行钱包使用高级教程

### ISSUE THREAD

**Issue by secp256** [gxchain/docs#13]
建议增加cli_wallet相关的高级教程，提供给有特殊需求的开发者，内容包括：
- 新钱包设置、私钥导入
- 常用的查询方法
- 高级操作，如发起提案、手工构造一笔交易并广播等

**Comment by shan-que** [comment]
已添加到高级教程分类下

**Comment by lanhaoxiang** [comment]
建议新增升级账户、注册新账户、交易历史接口描述

**Comment by shan-que** [comment]
升级账户，注册账户，交易历史接口已添加到高级教程。
