### ISSUE TITLE
添加智能合约表迁移相关文档

### ISSUE THREAD

**Issue by lanhaoxiang** [gxchain/docs#15]
## 问题描述
在开发过程中存在表结构升级或改动的情况，

## 问题解决
对于这样的情况：
1. 建立新的数据结构，保留老的原始结构
2. 迁移数据
3. 删除老的数据

## 最佳实践
1. 在迁移过程中需要停止新数据的插入，通过升级合约，利用一个flag来控制合约方法是否可以调用
2. 建议在迁移后先保留历史数据，或者删除表之前先备份历史数据

**Comment by shan-que** [comment]
已更新
