### ISSUE TITLE
get_balance缺少参数问题

### ISSUE THREAD

**Issue by dremofly** [gxchain/docs#9]
**Describe the bug**
在文档[如何搭建私有链](https://docs.gxchain.org/zh/advanced/private_chain.html#_2-%E7%94%B3%E9%A2%86%E5%88%9D%E5%A7%8B%E4%BD%99%E9%A2%9D)中的**2）申领余额**部分。使用给出的命令出现缺少参数的问题。
![image](https://user-images.githubusercontent.com/21236768/54973954-22aa8000-4fcd-11e9-9c4e-949cfdda3509.png)
我查看`help`发现缺少了参数`broadcast`。所以这里修改为
``` shell
unlocked >>> import_balance nathan ["5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"] true
```

**Comment by secp256** [comment]
@dremofly thank you
